version: '3.9'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://dbmysql:3306/adgan
      - DATABASE_USERNAME = admin
      - DATABASE_PASSWORD = admin
    depends_on:
      - dbmysql
  dbmysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'adgan'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'